### PR TITLE
Replace Opening Books

### PR DESCRIPTION
**Pull request by djdekker**
Replace opening books Fun, Anand, Korchnoi, Larsen and Pro by five
opening books covering ECO volumes A, B, C, D and E.

### CODE REVIEW

**Comment by ifekali** [comment]
I strongly object against removing Fun opening book. I often play against it.

> On 22. maj 2015, at 21.35, DJ Dekker <notifications@github.com> wrote:
> 
> Replace opening books Fun, Anand, Korchnoi, Larsen and Pro by five
> opening books covering ECO volumes A, B, C, D and E.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/jromang/picochess/pull/81
> 
> Commit Summary
> 
> 	• Replace Opening Books
> File Changes
> 
> 	• A books/a-flank.bin (0)
> 	• D books/a-fun.bin (0)
> 	• D books/b-anand.bin (0)
> 	• A books/b-semiopen.bin (0)
> 	• D books/c-korchnoi.bin (0)
> 	• A books/c-open.bin (0)
> 	• A books/d-closed.bin (0)
> 	• D books/d-larsen.bin (0)
> 	• A books/e-indian.bin (0)
> 	• D books/e-pro.bin (0)
> Patch Links:
> 
> 	• https://github.com/jromang/picochess/pull/81.patch
> 	• https://github.com/jromang/picochess/pull/81.diff
> —
> Reply to this email directly or view it on GitHub.
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
Of course, I very like the inclusion of the ECO books. 

Meybe we could ditch Performance or  GM1950 instead?

On 22. maj 2015, at 21.39, Jonas Žnidaršič <jonas@jonas.si> wrote:
> 
> 
> I strongly object against removing Fun opening book. I often play against it.

Meybe we could ditch Performance or  GM1950 instead?

- 
Izmet Fekali

**Comment by ifekali** [comment]
How about this?:

1. ECO flank
2. ECO semi
3. ECO open
4. ECO closed
5. ECO indian
6. gm2001
7. varied
8. fun
9. Stockfish
nobook

> On 22. maj 2015, at 21.43, Jonas Žnidaršič <jonas@jonas.si> wrote:
> 
> Meybe we could ditch Performance or  GM1950 instead?

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by sshivaji** [comment]
GM1950 is better than GM2001, as its all GM games from 1950 till 2013 :)

**Comment by sshivaji** [comment]
Can I pull the request now or are you planning to make a book change first?

**Comment by ifekali** [comment]
Ok, I propose this then, a bit shuffled:

1. ECO flank
2. ECO semi
3. ECO open
4. ECO closed
5. ECO indian
6. fun
7. varied
8. gm1950
9. performance (or pro, whichever better)
10. Stockfish
nobook

> On 22. maj 2015, at 22.43, Shivkumar Shivaji <notifications@github.com> wrote:
> 
> GM1950 is better than GM2001, as its all GM games from 1950 till 2013 :)
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by djdekker** [comment]
Would the issue be solved if we did the following?
1. delete f-gm2001.bin and
2. rename a-fun.bin to f-fun.bin

**Comment by ifekali** [comment]
Let's wait a bit, ... I prefer he reshuffles if agreed ...

> On 22. maj 2015, at 22.43, Shivkumar Shivaji <notifications@github.com> wrote:
> 
> Can I pull the request now or are you planning to make a book change first?
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
This works for me.

> On 22. maj 2015, at 22.57, DJ Dekker <notifications@github.com> wrote:
> 
> Would the issue be solved if we did the following?
> 1. delete f-gm2001.bin and
> 2. rename a-fun.bin to f-fun.bin
> 
> 

- 
Izmet Fekali

**Comment by djdekker** [comment]
I've just added a second commit to this pull request, proposing the replacement of f-gm2001.bin by f-fun.bin.

**Pull request merged**
