### PR TITLE
adds SMTP delivery of a finished game

### PR DESCRIPTION
**Pull request by raimarHD**
Hey friends,

this is my first Python based pull request for PicoChess. :-) Please don't punish me for not so good Python style.

Functional change:
This patch adds the ability to send a finished game via a regular SMTP mail server instead of using Mailgun Webservice. 
It is necessary to enter the options for the SMTP server via picochess.ini or command line. See "picochess.py" for additional required parameters.

Testing:
This patch was tested successfully with internet connection with an SSL and a non-SSL stmp server.
If no internet connection is available the failure of SMTP delivery will only be logged to the logfile but no error is given to the user or any other program interruption. 
I removed the Mailgun service due to not having an access to it. I am pretty sure that both services (Mailgun and SMTP) can stay aside.

Next steps:
If this patch fits to the upstream release of PicoChess an update of documentation is required and will be provided by myself.

Finally:
I hope you like and it works with your installation as well as with mine. 

Best,
Raimar

### CODE REVIEW

**Comment by raimarHD** [comment]
Thanks to landscape-bot, it showed an variable misspelling error within the SMTP error handling. Now fixed.

**Comment by sshivaji** [comment]
Thanks a lot for the code change! Will test it out today and integrate right away.

My first concern is to get in more working features before thinking about coding style. Jean-Francois might have different opinions :)

Shiv

**Comment by sshivaji** [comment]
I merged this in to master for testing:

Questions/Comments:

1. Can we assume the key or SMTP credentials are stored in the root directory (and thus deployed with the picochess image)? Should we check that they exist at a specified location?
2. I would prefer mailgun but happy to test with SMTP.

**Comment by sshivaji** [comment]
One more comment is that we should not remove mailgun but move it to a different setting to allow for both.

**Comment by raimarHD** [comment]
I submit a patch that allows both Mailgun and SMTP mail delivery. 
Regarding an PicoChess image I would suggest to include a picochess.ini with the parameters but not with any credentials. If a user wants to use it, he needs to write the key. :-)
picochess.ini: If you don't mind I'll write a "picochess.ini.example" to be added to the rep and to the image. The aim would be to describe within this file all options of PicoChess. The user can copy this file to picochess.ini and change the values. If something breaks the user can return to "picochess.ini.example" and start again.

**Comment by sshivaji** [comment]
I think it's ok to put in the key in the image for user friendliness. 

We can support changing the key or configuring SMTP using the web interface.

**Comment by ifekali** [comment]
Let's first update the documentation on this. I wasn't even aware that emailing the PGN was possible.

> On 17. maj 2015, at 20.26, Shivkumar Shivaji <notifications@github.com> wrote:
> 
> > picochess.ini: If you don't mind I'll write a "picochess.ini.example" to be added to the rep and to the image. The aim would be to describe within this file all options of PicoChess. The user can copy this file to picochess.ini and change the values. If something breaks the user can return to "picochess.ini.example" and start again.

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
Guys, until the documentation is done on this, I am very reluctant to include any of it in new images.

**Comment by ifekali** [comment]
I tried to test this but failed, as soon as I add smpt related lines to picochess.ini, it refuses to start at all.

Also, when is the pgn email send triggered? On mate only or also on setting up starting position again?

**Comment by raimarHD** [comment]
The event is only fired if the game is finished. See line 49 at pgn.py. The if structure will be evaluated and executed. So at startup no smtp related python code is executed. 
What is your error message while starting PicoChess?

**Comment by ifekali** [comment]
I don't know, as it is darn complicated to get the log. A button retrieving the last 50 lines of log in the web GUI would make this very much easier.


> On 20. maj 2015, at 14.18, Raimar Goldschmidt <notifications@github.com> wrote:
> 
> What is your error message while starting PicoChess?
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
I will try again tonight.

As far as I can remember, my picochess.ini looked pretty much exactly as Raimar's example script suggests (with gmail smtp). However, picochess refused to start even.

> On 20. maj 2015, at 14.18, Raimar Goldschmidt <notifications@github.com> wrote:
> 
> What is your error message while starting PicoChess?
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by raimarHD** [comment]
Do you have a Mailgun key set with your picochess.ini?

**Comment by ifekali** [comment]
I do not.

> On 20. maj 2015, at 15.00, Raimar Goldschmidt <notifications@github.com> wrote:
> 
> Do you have a Mailgun key set with your picochess.ini?
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by raimarHD** [comment]
Hi Jonas,
I tried to reproduce. With the example of the ini file I was able to crash PicoChess during startup with using the log-file option near the end of the ini file and pointing to a path that does not exist. This will crash PicoChess. Needs to be fixed.

**Comment by ifekali** [comment]
I got smtp emailing to work. I was using

smtp_encryption = true

instead of plain 

smtp_encryption

in picochess.ini. Please document your features ASAP in the future, it is frustrating to hunt. Please understand that testing anything is very time consuming, as we have a variety of hardware to try in all kinds of combinations (Pi model B, Pi model 2, USB board, bluetooth board, Revelation II, XL clock, 3000 clock).

(BTW, how buttons work is still NOT documented. Please somebody do it.)

> On 20. maj 2015, at 14.18, Raimar Goldschmidt <notifications@github.com> wrote:
> 
> The event is only fired if the game is finished. 

Hmm, this doesn't seem practical. When I play, the game is usually over with me resigning, it seems a waste of time to play it to a mate. Would it be feasible that pgn of a previous game is sent when a new game is setup (starting position)? Or maybe upon a button press on the clock?

- 
Jonas Žnidaršič
jonas@jonas.si

**Pull request merged**
