### PR TITLE
Always at least log to stdout

### PR DESCRIPTION
**Pull request by niklasf**
At the moment it's either stdout or a log file. Let's log to both (if a log file is configured) but always at least to stdout.

### CODE REVIEW

**Comment by LocutusOfPenguin** [comment]
H

**Comment by LocutusOfPenguin** [comment]
Hallo Niklas,

can y tell me why y want to change that?
For me making things more complex. For example with keyboard.py (=getting the messages there)

**Comment by niklasf** [comment]
Hi. I don't understand. What will be different in keyboard.py?

**Comment by sshivaji** [comment]
I think its useful to have output both at stdout and log file. Jurgen, let us know why it will be more complex?

**Comment by LocutusOfPenguin** [comment]
i often DONT have a dgt board with me. So, i use keyboard.py to dev&debug picochess.
In this situation i start the program in one terminal, and "tail -f picochess.log" in another.

Now: when there is a python (syntax) error, i see that in first very easily (even mins later). Only errors are displayed...very easy to see them.
Next: i often need the board-display and the printed fen. In your solution the display is "disturbed" by alot of log messages always move the display up. Therefore i use the term "complex".

If i'm only interested in playing and btw. hunting errors i don't need the second one. You see, its my choice, what i want. Starting the second terminal stuff is what is the ADVANTAGE of your version. I don't see something else, and therefore i asked WHY. I want to learn something, not complain.

My solution:
Perhaps you can implement a switch to turn stdout output on (i prefer its disabled in standard - see above, ha).

Jürgen

**Comment by niklasf** [comment]
Thanks for clarifying this. I'll open an improved PR soon.

**Pull request closed without merging**
