### PR TITLE
Engine name in pgn output

### PR DESCRIPTION
**Pull request by djdekker**
Sometimes I play against another engine than Stockfish (recently compiled Arasan 17.5 for Raspberry Pi). This code proposal puts the engine name in the pgn output instead of just “PicoChess”.

To be able to change engines correctly, it was necessary to delete the -e option from /etc/init.d/picochess and instead use the engine option in picochess.ini.

The Arasan engine gets installed in the /usr/local/bin/Arasan-17.5.0 directory by default, so I created a symbolic link in /opt/picochess/engines. Now in picochess.ini it is enough to write engine = arasanx.

### CODE REVIEW

**Comment by ifekali** [comment]
Yes, I did this and planned to include it in next image

> On 15. jun. 2015, at 21.24, DJ Dekker <notifications@github.com> wrote:
> 
> To be able to change engines correctly, it was necessary to delete the -e option from /etc/init.d/picochess and instead use the engine option in picochess.ini.
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
Doesn't work for me. I tested your code and this the email I got:

[Event "PicoChess game"]
[Site "?"]
[Date "2015.06.15"]
[Round "?"]
[White "izmet"]
[Black "games.pgn"]
[Result "*"]

1. e4 e6 2. h4 d5 *

> On 15. jun. 2015, at 21.24, DJ Dekker <notifications@github.com> wrote:
> 
> This code proposal puts the engine name in the pgn output instead of just “PicoChess”.
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
If I request PGN from web interface, it still lists opponents as "User" and "Picochess" as before.

In contrast, this is the output I used to get before via email:

[Event "PicoChess game"]
[Site "Ljubljana, Slovenia SI"]
[Date "2015.06.15"]
[Round "?"]
[White "izmet"]
[Black "PicoChess"]
[Result "*"]

1. e4 c5 2. h4 Nc6 *

(Note that PGN fetched from web interface always listed me as "User" and neved listed the Site location. PGN's from web and email were always different. Is this a feature or a bug?)




> On 15. jun. 2015, at 21.48, Jonas Žnidaršič <jonas@jonas.si> wrote:
> 
> Doesn't work for me. I tested your code and this the email I got:

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by djdekker** [comment]
I'm sorry... in line 32 of pgn.py the pgn_file_name should come first and engine_name second. I added a fix for this.

**Comment by ifekali** [comment]
This seems better, yes, but the change applies only to PGN's fetched via email. PGN fetched via web interface still lists "User" and "Picochess" ...

This is what I get via email:

[Event "PicoChess game"]
[Site "Ljubljana, Slovenia SI"]
[Date "2015.06.15"]
[Round "?"]
[White "izmet"]
[Black "Stockfish 150215"]
[Result "*"]

1. h4 e5 2. e4 Nf6 *

... and this is what I get via web interface:

[Event "Game"]
[Site "Ljubljana, Slovenia SI"]
[Date "????.??.??"]
[Round "?"]
[White "User"]
[Black "Picochess"]
[Result "*"]
[WhiteElo "*"]
[BlackElo "2900"]
[EventDate "2015-06-15"]

1. h4 e5 2. e4 Nf6 *



(BTW, note that the web PGN lists "User" as White always, even when user plays Black. Definitely a bug.)

 
> On 15. jun. 2015, at 22.00, DJ Dekker <notifications@github.com> wrote:
> 
> I'm sorry... in line 32 of pgn.py the pgn_file_name should come first and engine_name second. I added a fix for this.
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Pull request merged**
