### PR TITLE
updated dutch language

### PR DESCRIPTION
**Pull request by lucasvdp**

### CODE REVIEW

**Comment by djdekker** [comment]
To me it looks rather peculiar to write 'tijd' as 'tyd' and 'partij' as 'party' (which, BTW, means 'celebration' rather than 'game')... Why do you prefer 'tyd' and 'party' over the correct spelling?

**Comment by lucasvdp** [comment]
Because of the very limited 14 segment display of the dgt3000 tijd looks like “ti Jd”. In Dutch you can write the ij as a single letter which looks like the y on a 14 segment. You should not look at the messages in a normal font but in a 14 segment font. By the way, in German game is translated to Spiell, which do you prefere? Spel or partij?

Regards,

Lucas
Van: DJ Dekker [mailto:notifications@github.com]
Verzonden: dinsdag 19 april 2016 20:39
Aan: jromang/picochess <picochess@noreply.github.com>
CC: Lucas van der Ploeg | DGT <lucas@dgtprojects.com>
Onderwerp: Re: [jromang/picochess] updated dutch language (#180)


To me it looks rather peculiar to write 'tijd' as 'tyd' and 'partij' as 'party' (which, BTW, means 'celebration' rather than 'game')... Why do you prefer 'tyd' and 'party' over the correct spelling?

**Comment by djdekker** [comment]
Now I see what you mean! :)

I have a DGT 3000 clock with old firmware. It displays only capital letters, so "ti Jd" never occurs here. But on newer clocks you are absolutely right: "ti Jd" looks rather strange.

I prefer "partij" to "spel", because a "schaakpartij" is a game of chess and "schaakspel" is either chess-in-general (as in "Dit spel is lang geleden bedacht.") or a board with pieces (as in "DGT maakt prachtige schaakspellen."). Just my 2 cents.

**Comment by LocutusOfPenguin** [comment]
merged inside already. Thx

**Pull request closed without merging**
