### PR TITLE
Bug #124, fix to engine list sorting, shutdown from clock

### PR DESCRIPTION
**Pull request by pablo2000**
As above.

### CODE REVIEW

**Comment by LocutusOfPenguin** [comment]
Hi pablo,

i found following (2) errors:

- pressing the ">" button when in engine sometimes gets a nonetype error at engine_name = engine.get().name

- sometimes showing ONLY "ok", sometimes "ok" & result/current value. Level&Time for example behaves different. Should be all same.
I think "engine" is same (cause i only have one, cant check)


Also im not too happy with "shutdown". This is a dangerous function...We had that before on buttons, but removed it again. I would do it again (=remove!), or implement it with "two buttons at same time" press. For me its more harm then use.

Jürgen

**Comment by djdekker** [comment]
In earlier versions the board could become unresponsive after some time and it was useful to have a shutdown/reboot function with the clock buttons. I'm not experiencing these problems anymore. There are two ways to shut down the system with the white king+queen, which is enough for me.
If a clock based shutdown function is still necessary (which it might be to some users), then I'd suggest to put them in a menu with three options: 'restart Picochess' - 'reboot' - 'shutdown'.

**Comment by pablo2000** [comment]
Although I haven't come across the nonetype exception in testing, there was a possible condition where due to multiple button presses (or switch bounce), new requests for engine operations could arrive before the new engine is fully in place and so could generate odd errors like this. I have corrected it such that while the engine is shutdown and reloading all button presses are locked out. This is how it should be.
I have made the feedback messages all behave the same - it was 'level' and 'book' that generated multiple messages.
As to the shutdown, I have commented it out in the code and there can be some discussion about what to do. I cannot think it does more harm than "reboot" which is in the current code. I do, and I'm sure some others would (on the basis I'm not a special case), use it to shut the system down whilst leaving the position on the board untouched, for continued use later, either a game or analysing other games or whatever - you just can't do that with shutdown from the board. I got tired of using my cell phone to snap a photo of the position, reset the board to start position, do the queen-queen thing, get my photo and copy it back onto the board by hand ready for later.
Anyway, it's commented out in the code (I can just reinstate it and carry on with it at home) until there is a firm view as to which way to go. Perhaps a .ini file option to enable a 'power' menu??

Pablo

**Comment by LocutusOfPenguin** [comment]
yes, i just saw "reboot" still there :-( For sure, my answer is same...so you are right.

I just wish, i cant press all this dangerous function by *accident*. If there is a "shutdown" in display, and i must press another confirm button it should be okay.
I hate to stop my machine, cause im too stupid to know where i am...but if i do this error, others prob. also have this problem ;-)

Jürgen

**Comment by pablo2000** [comment]
I totally get why it may be a problem.

Confirm key is a good idea though and easy to do.... I'll drop that in tomorrow morning!

Pablo

**Pull request merged**
