### PR TITLE
Suggestion: Drop published libs in favor of using pip

### PR DESCRIPTION
**Pull request by niklasf**
Can I convince you to drop published libraries from the libs from the libs directory? This is just a suggestion - as always feel free to reject this.

It's a lot cleaner to keep track of dependencies using `pip`. The workflow using `pip` would then be:

Install all dependencies:
```
$ pip install --upgrade -r  requirements.txt
[...]
Cleaning up...
```

List installed dependencies:
```
$ pip list
crypto (1.4.1)
ecdsa (0.11)
Flask (0.10.1)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
Naked (0.1.31)
paramiko (1.15.2)
pip (1.5.6)
pycrypto (2.6.1)
pyserial (2.7)
python-chess (0.11.1)
PyYAML (3.11)
requests (2.7.0)
setuptools (18.0.1)
shellescape (3.4.1)
spur (0.3.14)
tornado (4.2.1)
Werkzeug (0.10.4)
```

List just the ones that need an update:
```
$ pip list --outdated
ecdsa (Current: 0.11 Latest: 0.13)
setuptools (Current: 18.0.1 Latest: 18.3.1)
pip (Current: 1.5.6 Latest: 7.1.2)
```

Upgrade:
```
$ pip install --upgrade ecdsa
Downloading/unpacking ecdsa from https://pypi.python.org/packages/2.7/e/ecdsa/ecdsa-0.13-py2.py3-none-any.whl#md5=a325d50195d049599f9b578ec4417bc6
  Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB): 86kB downloaded
Installing collected packages: ecdsa
  Found existing installation: ecdsa 0.11
    Uninstalling ecdsa:
      Successfully uninstalled ecdsa
Successfully installed ecdsa
Cleaning up...
```

Do some testing. Then save current versions to `requirements.txt`:
```
pip freeze > requirements.txt
```

### CODE REVIEW

**Comment by sshivaji** [comment]
I am fine with this. Did you mean to put in requirements.txt?

Jean-Francois initially put in the libs for ease of upgrade when using the DGT clock amongst other reasons. If upgrade can work well (can't be a simple git pull this time), then we can go ahead with your proposal.

Shiv

**Comment by LocutusOfPenguin** [comment]
I tried install your requirement.txt file...moved the lib away (but leave chesstalker...this lib is not somewhere else i guess => maybe another problem?) and do a
"sudo pip3 install --upgrade -r requirement.txt"

Then start picochess on keyboard mode, and get this error message:

Traceback (most recent call last):
  File "./picochess.py", line 689, in <module>
    main()
  File "./picochess.py", line 446, in main
    game = handle_move(result, game)
  File "./picochess.py", line 379, in handle_move
    think(game, time_control)
  File "./picochess.py", line 241, in think
    book_move = searchmoves.book(book, game)
  File "./picochess.py", line 57, in book
    bm = bookreader.weighted_choice(game, self.excludemoves)
  File "/usr/local/lib/python3.4/dist-packages/chess/polyglot.py", line 194, in weighted_choice
    choice = random.randint(0, total_weights - 1)
AttributeError: 'set' object has no attribute 'randint'

Moving the lib folder back...everything fine again.
Seems there is a "random" missing, no?

Jürgen

**Comment by niklasf** [comment]
@sshivaji: Yeah, I force pushed it right after, but somehow GitHub has trouble updating that huge diff. It's on the branch, though.

@LocutusOfPenguin: The officially released python-chess does not yet have the excludemoves feature. Probably the one from the libs directory has this already. So the keyword argument random gets overriden instead:

 `choice(self, board, minimum_weight=1, random=...)` # 0.11.1
 `choice(self, board, minimum_weight=1, exclude_moves=set(), random=...)` # master

**Comment by LocutusOfPenguin** [comment]
yes, that's the problem...no "exclude_moves" (i just checked on /usr...)

but what should i do, when we really do your suggest, and i want to be on the cutting edge like now?

**Comment by niklasf** [comment]
That would be:

```
pip install -e git+https://github.com/niklasf/python-chess.git@11a671c3b99ac6b990af4e7b9740e18e5056104b#egg=python-chess
```

You can also use a branch or tagname instead. This also checks out a local copy were you can experiment with live edits.

**Comment by LocutusOfPenguin** [comment]
Thanks niklas.
I don't want to experiment, just bring it back to a working stage, so i followed a 
"pip3 install --upgrade python-chess" to really get it to work => what to do with this "src"?
That's easy for you...but for me, it wasn't clear at first spot since i don't know "pip" at all:-)

Now system is in better shape(!) but it was abit harder for me, to reach it...ha

Can this "chesstalker" also be changed to "pip"? Would make sense to have all behaves same.

**Comment by niklasf** [comment]
It's always some extra effort learning new tools and workflows. [Slightly relevant xkcd](https://xkcd.com/1205/).

I added the src folder to `.gitignore`. You don't have to do anything with it.

It looks to me like chesstalker is really specific to picochess and not it's own independent library. Probably it shouldn't have been in libs in the first place (?).

ConfigArgParse [is a thing](https://pypi.python.org/pypi/ConfigArgParse/0.9.1), so we could use the published library.

**Comment by LocutusOfPenguin** [comment]
Hi,
y misunderstood me: "what to do with src" => running your "-e" command, and now? To make it work, i have to transfer this src somehow to the correct place, and for this i seem to need this "install" command. But on my laptop at home btw. not working (it stays on old lib - without any errors).

Perhaps you can write a docu how to install picochess from scratch (with pip!). The "installation.rst" seems to be outdated anyway - for all this not so experienced users like me ;-)
see here: http://docs.picochess.org/en/latest/installation.html#manual-installation

Jürgen

**Comment by niklasf** [comment]
Hi. I will do that. Actually python-chess should automatically be sourced from that src directory. Can you please check `pip list`?

Expected is something like:
```
python-chess (0.11.1, /home/niklas/Projekte/picochess/src/python-chess-master)
```

**Comment by LocutusOfPenguin** [comment]
Im not at home (this computer here, worked ... there is the newest lib from you installed).
pip3 list|grep "chess"
only gives me:
python-chess (0.11.1)

no path

**Comment by niklasf** [comment]
Can you try to first uninstall when you get home? `pip uninstall python-chess`.

**Comment by LocutusOfPenguin** [comment]
after many tries with "uninstall" &  "install -e" stuff inside the "lib/python3.4" dir >> i get this:
pip3 list |grep "chess"
>> python-chess (0.11.1, /usr/local/lib/python3.4/src/python-chess)

move "picochess/libs/chess" away, and run picochess....all fine, he using the new installed "-e lib".

(for test!) pip3 uninstall python-chess
>> Can't uninstall 'python-chess'. No files were found to uninstall. ARGH
btw. "/usr/local/lib/python3.4/src" isnt deleted, as said from "pip-delete-this..." file. Hmm

I don't have the time for this fiddle, sorry. Am i too stupid for this "pip"??
I give up, and wait for a step-by-step docu.. to clear all (seems to be important), and then do 1:1 and "happy, its working like it is right now with /libs inside a picochess folder" ;-)

**Comment by sshivaji** [comment]
Instead of using global pip, it might be easier to use a virtual env. I have the virtual env thing working in other chess projects such as kivy chess. Niklas, let me know if you want me to help with virtual env config.

**Comment by niklasf** [comment]
@sshivaji: That's great. (I just didn't want to bring up too many things at once.) Are there any problems when you try to use virtualenv with picochess? It works for me using the `requirements.txt` from this PR.

**Comment by sshivaji** [comment]
You can use something like this - https://github.com/sshivaji/kivy-chess/blob/master/virtualenv.py





and a corresponding https://github.com/sshivaji/kivy-chess/blob/master/install.sh





It does not have to be as complex as the kivy chess setup. install.sh can simply be 2 lines:




python virtualenv.py chesspython

chesspython/bin/pip install -r requirments.txt








—

**Comment by niklasf** [comment]
We shouldn't check in virtualenv itself. It can be installed globally using pip or the [python3-virtualenv](https://packages.debian.org/de/jessie/python3-virtualenv) package.

**Comment by sshivaji** [comment]
Interesting, did not realize that. I saw that another project had virtualenv.py. However, global install seems better.




Shiv


—

**Comment by niklasf** [comment]
64accf1 (included in this PR) updates the installation instruction and also has an optional step for virtualenv.

**Comment by sshivaji** [comment]
I will test this and merge soon, thx

**Comment by pablo2000** [comment]
As the libs are no longer directly contained in the picochess repo, I guess we need to modify the auto-update code in picochess.py, for the event that new code requires new published libs??

**Comment by sshivaji** [comment]
It would have to do “pip install -r requirements.txt”


Shiv


—

**Comment by pablo2000** [comment]
Yes. With --upgrade, I think. 

I'll add it to the to-do list.

**Comment by sshivaji** [comment]
Good point.




Thanks, Shiv


—

**Pull request merged**
