### PR TITLE
Added Resign / Draw to DGT convention

### PR DESCRIPTION
**Pull request by pablo2000**
Most games are resigned, but Pico requires a mate or records an abort, which is annoying if you upload your games to a database
of some sort for analysis.

Now, during a game, placing the two kings on opposite centre squares will signal a resignation:
* If both kings on white, the result is white wins and the game recorded 1-0
* If both kings on black, the result is black wins and the game recorded 0-1

Placing the kings on adjacent centre squares on the same rank signals a draw and the game recorded 1/2-1/2.

The 4 and 5 rank must be clear of other pieces - only kings.

It's your decision when to declare a win or draw - be honest with yourself about whether you would have drawn
or lost :)

### CODE REVIEW

**Comment by sshivaji** [comment]
Pablo, thanks for all of your commits. Great stuff!

**Comment by pablo2000** [comment]
Hey it's a great little project - love it!

I have plenty more in the pipeline...

Pablo

**Comment by ifekali** [comment]
Github shows me (ifekali) updating some python code, but it was NOT ME (I can't code in python, I'm just a tester). How it this possible? For example, who did these changes (certainly not me):

https://github.com/jromang/picochess/commit/c7d58cf6b0d266eeb7b7f1893b434ec0613fb46e

Somebody knows my login credentioals? HOW????


> On 19. avg. 2015, at 23.26, Pablo <notifications@github.com> wrote:
> 
> Hey it's a great little project - love it!

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by pablo2000** [comment]
Hi all

I don't have your credentials. For some reason when I make a pu request from my repository, it comes up with that username. Tbh I'm a little new to GitHub, although not Git, so I may have something set wrong - but I don't think so. I presumed it was just setup that way. 

Advice welcome if it's me. 

Pablo

**Comment by LocutusOfPenguin** [comment]
Hey Jonas,

im happy we now have two more coders here (pablo & you).
Seriously:
I would wild guess, its a bug from github for the moment , mixing pablo commits with your id.
Happened already twice.

**Pull request merged**
